tests/integration/test_charm.py
tox.ini

- Update of https://github.com/canonical/metacontroller-operator/pull/6 according to latest Observability Team's review: removed the direct relation between prometheus and metacontroller-operator.
- Unpinned `black==20.8b1` version

Removed prometheus-app direct relation in test, unpinned black version

---

.github/workflows/publish.yaml
.github/workflows/release.yaml
src/charm.py
tox.ini

Add new release charm action and some lint fixes. Update publish action to use `upload-charm` as the release action need the release info from that action. 
It's using the release charm action from [promote-charm branch](https://github.com/canonical/charming-actions/tree/promote-charm). This would be updated in the future to use stable version

test release charm action

---

.github/workflows/integrate.yaml
.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
.github/workflows/weekly_ci.yaml
lib/charms/prometheus_k8s/v0/prometheus_scrape.py

Charming actions updated according to the ones agreed on template-operator charm.
The aim was to:
- update release charm action
- have two publish actions for `on: push` and `on: pull_request`:
- on pull_request, publish to branch no matter if tests passed (tests and publish should run simultaneously)
- on push, publish to latest/edge only if tests passed
- avoid re-running the tests on pull_request
- use reusable workflows in order to avoid duplication of code.
Note: this is a single-charm repo with no resources.

Update charming actions

---

src/charm.py
tests/unit/render_resource/simple_manifest_result.yaml
tests/unit/test_charm.py

This change should not change any function, but will mean we don't need to edit tests every time we bump the image version
merge after #18

refactor: change unit tests so they don't break on version bumps

---

.github/workflows/integrate.yaml

Update ci to use microk8s 1.22/stable
ci fails because of slashes in branch name when publishing charm. Tests passed.

update microk8s version

---

src/prometheus_alert_rules/unit_unavailable.rule

As stated in issue https://github.com/canonical/bundle-kubeflow/issues/564 the duation for alerts for argo is set to 0m, which is too low for prod environments. We need to change to at least 5m to prevent the flapping behavior.
Partial-Bug: https://github.com/canonical/bundle-kubeflow/issues/564

Changed unit_unavailable interval for prometheus

---

tools/get-images-1.7-stable.sh

Repository specific list of images.
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup.
Summary of changes:
- Added script that retrieves image managed by charm.

feat: retrieve images

---

tools/get-images.sh

Used by CVE scanning workflows and can be used to collect images URL for airgapped setup. Script is specific for track/2.0 branch to capture all images for that branch. Branch is handled in kubeflow-ci and bundle automation using bundle file.
Summary of changes:
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.

feat: updated get images script without branch checkout for track/2.0

---

src/charm.py

Upgrade metacontroller to v3.0.0. There are no other changes in the yaml files (based on comparison with this https://github.com/metacontroller/metacontroller/releases/tag/v3.0.0).

Upgrade metacontroller to v3.0.0

---

metadata.yaml
src/charm.py
tests/unit/test_charm.py

Expose the metacontroller OCI image in metadata.yaml, so that its value can be overwritten on deployment. Previously, the image was hardcoded in the charm code.
Closes #80

feat: Expose metacontroller image in metadata.yaml

---

config.yaml
metadata.yaml
src/charm.py
tests/unit/test_charm.py
tools/get-images.sh

Expose the metacontroller image in config.yaml, so that it can be set either pre or post deployment. This also ensures that the image is always pulled from the specified source and not a private registry, which the metacontroller StatefulSet doesn't have permission to access.
Refs #80

fix: Make the metacontroller image configurable

---

tests/integration/test_charm.py

This PR backports #82 needed for integration tests to succeed.
Refs https://github.com/canonical/bundle-kubeflow/issues/688
Refs https://github.com/canonical/bundle-kubeflow/issues/690

backport(fix): Pin Prometheus and Grafana revisions (#82)

---

config.yaml

To use decorator contoller in kfp-profiles-controller https://github.com/canonical/kfp-operators/pull/344 we need metacontroller v3.

Update image to v3.0.0

---

src/charm.py
src/files/manifests/metacontroller-svc.yaml
tests/integration/test_charm.py

This charm was not deploying any Service for the workload container, which is fine for its regular functions, but causes an issue when the Prometheus scraper tries reaching out the metrics endpoint. This commit adds a Service that is attached to the WORKLOAD (the container inside the Pod that gets created by the [StatefulSet](https://github.com/canonical/metacontroller-operator/blob/main/src/files/manifests/metacontroller.yaml) we are applying manually) so that its metrics can be reached correctly. 
Because of the above, the MetricsEndpointProvider's target has to be refactored to point to the correct service. In a previous version of this charm, the target was pointing to the charm's container, which does not have any metrics endpoit, causing the issues reported in …

fix: create a Service for the workload and fix the metrics collector

---

config.yaml

integrates metacontroller rock `v3.0.0` in the charm, built from the `On Push` of PR https://github.com/canonical/metacontroller-rock/pull/10

feat: use metacontroller rock v3.0.0

---

.github/workflows/publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate in track/3.0

---

terraform/variables.tf

There's a "typo" in the `variables.tf` where app_name defaults to `training-operator`.

fix(terraform): Set default value to `metacontroller-operator`

---

terraform/variables.tf

There's a "typo" in the variables.tf where app_name defaults to training-operator.

fix(terraform): Set default value to `metacontroller-operator` (backport from #131)

---

requirements-fmt.txt
requirements-integration.txt
requirements-lint.txt
requirements-unit.in
requirements-unit.txt
requirements.txt
tox.ini

* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
* Remove unused pytest-lazy-fixture package
* Bump chisme to 0.4.4 to fix #138
Ref canonical/bundle-kubeflow#1177
Ref canonical/bundle-kubeflow#1185
Fixes #138

chore: update python dependencies + pin pip

---

src/files/manifests/metacontroller-crds-v1.yaml
src/files/manifests/metacontroller-svc.yaml

I created this PR to update the manifest files, but they haven't changed since the previous versions.
For reference, the upstream manifests are located [here](https://github.com/kubeflow/manifests/tree/0259e7ba489672bb1cad4a6dd3227b71a498c95c/apps/pipeline/upstream/third-party/metacontroller/base).
Note that the new manifests have an added `securityContext` field, which I am not including, see the [track issue](https://github.com/canonical/kfp-operators/issues/675).

chore: Fix linting

---

src/files/manifests/metacontroller-rbac.yaml
tests/integration/test_charm.py

Closes https://github.com/canonical/metacontroller-operator/issues/157
1. Added RBAC permissions for ServiceAccounts and PodDefaults
2. Added small comments in those resources, so it's easier to detect we need them, so we don't accidentally delete them in the future
I tested the changes manually by:
1. Spinning up the `latest` bundle with
```bash
tox -vve test_bundle_deployment-latest -- --model kubeflow --keep-models -vv -s
```
2. Packed and deployhed the charm from this PR
The KFP PodDefault was there. I also deployed MLflow and related with KServe as well, and all Secrets, PodDefaults and ServiceAccounts were created as expected.
```bash
NAME                                 TYPE     DATA   AGE
kserve-controller-s3                 Opaque   2      17m
mlflow-server-minio-artifact …
```

fix: include necessary RBAC

---

requirements-integration.in
requirements-integration.txt

This PR updates `charmed_kubeflow_chisme` to fix https://github.com/canonical/charmed-kubeflow-chisme/issues/155

chore: Update `charmed_kubeflow_chisme` in requirements
